#include <clout/protocol/get_config.hpp>
#include <clout/protocol/config.hpp>
#include <clout/protocol/asset.hpp>
#include <clout/protocol/types.hpp>
#include <clout/protocol/version.hpp>

namespace clout { namespace protocol {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

#ifdef IS_TEST_NET
   result[ "IS_TEST_NET" ] = true;
   result["TESTNET_BLOCK_LIMIT"] = TESTNET_BLOCK_LIMIT;
#else
   result[ "IS_TEST_NET" ] = false;
#endif

   result["SMT_MAX_VOTABLE_ASSETS"] = SMT_MAX_VOTABLE_ASSETS;
   result["SMT_VESTING_WITHDRAW_INTERVAL_SECONDS"] = SMT_VESTING_WITHDRAW_INTERVAL_SECONDS;
   result["SMT_UPVOTE_LOCKOUT"] = SMT_UPVOTE_LOCKOUT;
   result["SMT_EMISSION_MIN_INTERVAL_SECONDS"] = SMT_EMISSION_MIN_INTERVAL_SECONDS;
   result["SMT_EMIT_INDEFINITELY"] = SMT_EMIT_INDEFINITELY;
   result["SMT_MAX_NOMINAL_VOTES_PER_DAY"] = SMT_MAX_NOMINAL_VOTES_PER_DAY;
   result["SMT_MAX_VOTES_PER_REGENERATION"] = SMT_MAX_VOTES_PER_REGENERATION;
   result["SMT_DEFAULT_VOTES_PER_REGEN_PERIOD"] = SMT_DEFAULT_VOTES_PER_REGEN_PERIOD;
   result["SMT_DEFAULT_PERCENT_CURATION_REWARDS"] = SMT_DEFAULT_PERCENT_CURATION_REWARDS;
   result["SMT_INITIAL_VESTING_PER_UNIT"] = SMT_INITIAL_VESTING_PER_UNIT;
   result["SMT_BALLAST_SUPPLY_PERCENT"] = SMT_BALLAST_SUPPLY_PERCENT;
   result["SMT_MAX_ICO_TIERS"] = SMT_MAX_ICO_TIERS;

   result["CBD_SYMBOL"] = CBD_SYMBOL;
   result["CLOUT_INITIAL_VOTE_POWER_RATE"] = CLOUT_INITIAL_VOTE_POWER_RATE;
   result["CLOUT_REDUCED_VOTE_POWER_RATE"] = CLOUT_REDUCED_VOTE_POWER_RATE;
   result["CLOUT_100_PERCENT"] = CLOUT_100_PERCENT;
   result["CLOUT_1_PERCENT"] = CLOUT_1_PERCENT;
   result["CLOUT_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = CLOUT_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
   result["CLOUT_ACTIVE_CHALLENGE_COOLDOWN"] = CLOUT_ACTIVE_CHALLENGE_COOLDOWN;
   result["CLOUT_ACTIVE_CHALLENGE_FEE"] = CLOUT_ACTIVE_CHALLENGE_FEE;
   result["CLOUT_ADDRESS_PREFIX"] = CLOUT_ADDRESS_PREFIX;
   result["CLOUT_APR_PERCENT_MULTIPLY_PER_BLOCK"] = CLOUT_APR_PERCENT_MULTIPLY_PER_BLOCK;
   result["CLOUT_APR_PERCENT_MULTIPLY_PER_HOUR"] = CLOUT_APR_PERCENT_MULTIPLY_PER_HOUR;
   result["CLOUT_APR_PERCENT_MULTIPLY_PER_ROUND"] = CLOUT_APR_PERCENT_MULTIPLY_PER_ROUND;
   result["CLOUT_APR_PERCENT_SHIFT_PER_BLOCK"] = CLOUT_APR_PERCENT_SHIFT_PER_BLOCK;
   result["CLOUT_APR_PERCENT_SHIFT_PER_HOUR"] = CLOUT_APR_PERCENT_SHIFT_PER_HOUR;
   result["CLOUT_APR_PERCENT_SHIFT_PER_ROUND"] = CLOUT_APR_PERCENT_SHIFT_PER_ROUND;
   result["CLOUT_BANDWIDTH_AVERAGE_WINDOW_SECONDS"] = CLOUT_BANDWIDTH_AVERAGE_WINDOW_SECONDS;
   result["CLOUT_BANDWIDTH_PRECISION"] = CLOUT_BANDWIDTH_PRECISION;
   result["CLOUT_BENEFICIARY_LIMIT"] = CLOUT_BENEFICIARY_LIMIT;
   result["CLOUT_BLOCKCHAIN_PRECISION"] = CLOUT_BLOCKCHAIN_PRECISION;
   result["CLOUT_BLOCKCHAIN_PRECISION_DIGITS"] = CLOUT_BLOCKCHAIN_PRECISION_DIGITS;
   result["CLOUT_BLOCKCHAIN_HARDFORK_VERSION"] = CLOUT_BLOCKCHAIN_HARDFORK_VERSION;
   result["CLOUT_BLOCKCHAIN_VERSION"] = CLOUT_BLOCKCHAIN_VERSION;
   result["CLOUT_BLOCK_INTERVAL"] = CLOUT_BLOCK_INTERVAL;
   result["CLOUT_BLOCKS_PER_DAY"] = CLOUT_BLOCKS_PER_DAY;
   result["CLOUT_BLOCKS_PER_HOUR"] = CLOUT_BLOCKS_PER_HOUR;
   result["CLOUT_BLOCKS_PER_YEAR"] = CLOUT_BLOCKS_PER_YEAR;
   result["CLOUT_CASHOUT_WINDOW_SECONDS"] = CLOUT_CASHOUT_WINDOW_SECONDS;
   result["CLOUT_CASHOUT_WINDOW_SECONDS_PRE_HF12"] = CLOUT_CASHOUT_WINDOW_SECONDS_PRE_HF12;
   result["CLOUT_CASHOUT_WINDOW_SECONDS_PRE_HF17"] = CLOUT_CASHOUT_WINDOW_SECONDS_PRE_HF17;
   result["CLOUT_CHAIN_ID"] = CLOUT_CHAIN_ID;
   result["CLOUT_COMMENT_REWARD_FUND_NAME"] = CLOUT_COMMENT_REWARD_FUND_NAME;
   result["CLOUT_COMMENT_TITLE_LIMIT"] = CLOUT_COMMENT_TITLE_LIMIT;
   result["CLOUT_CONTENT_APR_PERCENT"] = CLOUT_CONTENT_APR_PERCENT;
   result["CLOUT_CONTENT_CONSTANT_HF0"] = CLOUT_CONTENT_CONSTANT_HF0;
   result["CLOUT_CONTENT_CONSTANT_HF21"] = CLOUT_CONTENT_CONSTANT_HF21;
   result["CLOUT_CONTENT_REWARD_PERCENT_HF16"] = CLOUT_CONTENT_REWARD_PERCENT_HF16;
   result["CLOUT_CONTENT_REWARD_PERCENT_HF21"] = CLOUT_CONTENT_REWARD_PERCENT_HF21;
   result["CLOUT_CONVERSION_DELAY"] = CLOUT_CONVERSION_DELAY;
   result["CLOUT_CONVERSION_DELAY_PRE_HF_16"] = CLOUT_CONVERSION_DELAY_PRE_HF_16;
   result["CLOUT_CREATE_ACCOUNT_DELEGATION_RATIO"] = CLOUT_CREATE_ACCOUNT_DELEGATION_RATIO;
   result["CLOUT_CREATE_ACCOUNT_DELEGATION_TIME"] = CLOUT_CREATE_ACCOUNT_DELEGATION_TIME;
   result["CLOUT_CREATE_ACCOUNT_WITH_CLOUT_MODIFIER"] = CLOUT_CREATE_ACCOUNT_WITH_CLOUT_MODIFIER;
   result["CLOUT_CURATE_APR_PERCENT"] = CLOUT_CURATE_APR_PERCENT;
   result["CLOUT_CUSTOM_OP_DATA_MAX_LENGTH"] = CLOUT_CUSTOM_OP_DATA_MAX_LENGTH;
   result["CLOUT_CUSTOM_OP_ID_MAX_LENGTH"] = CLOUT_CUSTOM_OP_ID_MAX_LENGTH;
   result["CLOUT_DEFAULT_CBD_INTEREST_RATE"] = CLOUT_DEFAULT_CBD_INTEREST_RATE;
   result["CLOUT_DOWNVOTE_POOL_PERCENT_HF21"] = CLOUT_DOWNVOTE_POOL_PERCENT_HF21;
   result["CLOUT_EQUIHASH_K"] = CLOUT_EQUIHASH_K;
   result["CLOUT_EQUIHASH_N"] = CLOUT_EQUIHASH_N;
   result["CLOUT_FEED_HISTORY_WINDOW"] = CLOUT_FEED_HISTORY_WINDOW;
   result["CLOUT_FEED_HISTORY_WINDOW_PRE_HF_16"] = CLOUT_FEED_HISTORY_WINDOW_PRE_HF_16;
   result["CLOUT_FEED_INTERVAL_BLOCKS"] = CLOUT_FEED_INTERVAL_BLOCKS;
   result["CLOUT_GENESIS_TIME"] = CLOUT_GENESIS_TIME;
   result["CLOUT_HARDFORK_REQUIRED_WITNESSES"] = CLOUT_HARDFORK_REQUIRED_WITNESSES;
   result["CLOUT_HF21_CONVERGENT_LINEAR_RECENT_CLAIMS"] = CLOUT_HF21_CONVERGENT_LINEAR_RECENT_CLAIMS;
   result["CLOUT_INFLATION_NARROWING_PERIOD"] = CLOUT_INFLATION_NARROWING_PERIOD;
   result["CLOUT_INFLATION_RATE_START_PERCENT"] = CLOUT_INFLATION_RATE_START_PERCENT;
   result["CLOUT_INFLATION_RATE_STOP_PERCENT"] = CLOUT_INFLATION_RATE_STOP_PERCENT;
   result["CLOUT_INIT_MINER_NAME"] = CLOUT_INIT_MINER_NAME;
   result["CLOUT_INIT_PUBLIC_KEY_STR"] = CLOUT_INIT_PUBLIC_KEY_STR;
#if 0
   // do not expose private key, period.
   // we need this line present but inactivated so CI check for all constants in config.hpp doesn't complain.
   result["CLOUT_INIT_PRIVATE_KEY"] = CLOUT_INIT_PRIVATE_KEY;
#endif
   result["CLOUT_INIT_SUPPLY"] = CLOUT_INIT_SUPPLY;
   result["CLOUT_CBD_INIT_SUPPLY"] = CLOUT_CBD_INIT_SUPPLY;
   result["CLOUT_INIT_TIME"] = CLOUT_INIT_TIME;
   result["CLOUT_IRREVERSIBLE_THRESHOLD"] = CLOUT_IRREVERSIBLE_THRESHOLD;
   result["CLOUT_LIQUIDITY_APR_PERCENT"] = CLOUT_LIQUIDITY_APR_PERCENT;
   result["CLOUT_LIQUIDITY_REWARD_BLOCKS"] = CLOUT_LIQUIDITY_REWARD_BLOCKS;
   result["CLOUT_LIQUIDITY_REWARD_PERIOD_SEC"] = CLOUT_LIQUIDITY_REWARD_PERIOD_SEC;
   result["CLOUT_LIQUIDITY_TIMEOUT_SEC"] = CLOUT_LIQUIDITY_TIMEOUT_SEC;
   result["CLOUT_MAX_ACCOUNT_CREATION_FEE"] = CLOUT_MAX_ACCOUNT_CREATION_FEE;
   result["CLOUT_MAX_ACCOUNT_NAME_LENGTH"] = CLOUT_MAX_ACCOUNT_NAME_LENGTH;
   result["CLOUT_MAX_ACCOUNT_WITNESS_VOTES"] = CLOUT_MAX_ACCOUNT_WITNESS_VOTES;
   result["CLOUT_MAX_ASSET_WHITELIST_AUTHORITIES"] = CLOUT_MAX_ASSET_WHITELIST_AUTHORITIES;
   result["CLOUT_MAX_AUTHORITY_MEMBERSHIP"] = CLOUT_MAX_AUTHORITY_MEMBERSHIP;
   result["CLOUT_MAX_BLOCK_SIZE"] = CLOUT_MAX_BLOCK_SIZE;
   result["CLOUT_SOFT_MAX_BLOCK_SIZE"] = CLOUT_SOFT_MAX_BLOCK_SIZE;
   result["CLOUT_MAX_CASHOUT_WINDOW_SECONDS"] = CLOUT_MAX_CASHOUT_WINDOW_SECONDS;
   result["CLOUT_MAX_COMMENT_DEPTH"] = CLOUT_MAX_COMMENT_DEPTH;
   result["CLOUT_MAX_COMMENT_DEPTH_PRE_HF17"] = CLOUT_MAX_COMMENT_DEPTH_PRE_HF17;
   result["CLOUT_MAX_FEED_AGE_SECONDS"] = CLOUT_MAX_FEED_AGE_SECONDS;
   result["CLOUT_MAX_INSTANCE_ID"] = CLOUT_MAX_INSTANCE_ID;
   result["CLOUT_MAX_MEMO_SIZE"] = CLOUT_MAX_MEMO_SIZE;
   result["CLOUT_MAX_WITNESSES"] = CLOUT_MAX_WITNESSES;
   result["CLOUT_MAX_MINER_WITNESSES_HF0"] = CLOUT_MAX_MINER_WITNESSES_HF0;
   result["CLOUT_MAX_MINER_WITNESSES_HF17"] = CLOUT_MAX_MINER_WITNESSES_HF17;
   result["CLOUT_MAX_PERMLINK_LENGTH"] = CLOUT_MAX_PERMLINK_LENGTH;
   result["CLOUT_MAX_PROXY_RECURSION_DEPTH"] = CLOUT_MAX_PROXY_RECURSION_DEPTH;
   result["CLOUT_MAX_RATION_DECAY_RATE"] = CLOUT_MAX_RATION_DECAY_RATE;
   result["CLOUT_MAX_RESERVE_RATIO"] = CLOUT_MAX_RESERVE_RATIO;
   result["CLOUT_MAX_RUNNER_WITNESSES_HF0"] = CLOUT_MAX_RUNNER_WITNESSES_HF0;
   result["CLOUT_MAX_RUNNER_WITNESSES_HF17"] = CLOUT_MAX_RUNNER_WITNESSES_HF17;
   result["CLOUT_MAX_SATOSHIS"] = CLOUT_MAX_SATOSHIS;
   result["CLOUT_MAX_SHARE_SUPPLY"] = CLOUT_MAX_SHARE_SUPPLY;
   result["CLOUT_MAX_SIG_CHECK_DEPTH"] = CLOUT_MAX_SIG_CHECK_DEPTH;
   result["CLOUT_MAX_SIG_CHECK_ACCOUNTS"] = CLOUT_MAX_SIG_CHECK_ACCOUNTS;
   result["CLOUT_MAX_TIME_UNTIL_EXPIRATION"] = CLOUT_MAX_TIME_UNTIL_EXPIRATION;
   result["CLOUT_MAX_TRANSACTION_SIZE"] = CLOUT_MAX_TRANSACTION_SIZE;
   result["CLOUT_MAX_UNDO_HISTORY"] = CLOUT_MAX_UNDO_HISTORY;
   result["CLOUT_MAX_URL_LENGTH"] = CLOUT_MAX_URL_LENGTH;
   result["CLOUT_MAX_VOTE_CHANGES"] = CLOUT_MAX_VOTE_CHANGES;
   result["CLOUT_MAX_VOTED_WITNESSES_HF0"] = CLOUT_MAX_VOTED_WITNESSES_HF0;
   result["CLOUT_MAX_VOTED_WITNESSES_HF17"] = CLOUT_MAX_VOTED_WITNESSES_HF17;
   result["CLOUT_MAX_WITHDRAW_ROUTES"] = CLOUT_MAX_WITHDRAW_ROUTES;
   result["CLOUT_MAX_WITNESS_URL_LENGTH"] = CLOUT_MAX_WITNESS_URL_LENGTH;
   result["CLOUT_MIN_ACCOUNT_CREATION_FEE"] = CLOUT_MIN_ACCOUNT_CREATION_FEE;
   result["CLOUT_MIN_ACCOUNT_NAME_LENGTH"] = CLOUT_MIN_ACCOUNT_NAME_LENGTH;
   result["CLOUT_MIN_BLOCK_SIZE_LIMIT"] = CLOUT_MIN_BLOCK_SIZE_LIMIT;
   result["CLOUT_MIN_BLOCK_SIZE"] = CLOUT_MIN_BLOCK_SIZE;
   result["CLOUT_MIN_CONTENT_REWARD"] = CLOUT_MIN_CONTENT_REWARD;
   result["CLOUT_MIN_CURATE_REWARD"] = CLOUT_MIN_CURATE_REWARD;
   result["CLOUT_MIN_PERMLINK_LENGTH"] = CLOUT_MIN_PERMLINK_LENGTH;
   result["CLOUT_MIN_REPLY_INTERVAL"] = CLOUT_MIN_REPLY_INTERVAL;
   result["CLOUT_MIN_REPLY_INTERVAL_HF20"] = CLOUT_MIN_REPLY_INTERVAL_HF20;
   result["CLOUT_MIN_ROOT_COMMENT_INTERVAL"] = CLOUT_MIN_ROOT_COMMENT_INTERVAL;
   result["CLOUT_MIN_COMMENT_EDIT_INTERVAL"] = CLOUT_MIN_COMMENT_EDIT_INTERVAL;
   result["CLOUT_MIN_VOTE_INTERVAL_SEC"] = CLOUT_MIN_VOTE_INTERVAL_SEC;
   result["CLOUT_MINER_ACCOUNT"] = CLOUT_MINER_ACCOUNT;
   result["CLOUT_MINER_PAY_PERCENT"] = CLOUT_MINER_PAY_PERCENT;
   result["CLOUT_MIN_FEEDS"] = CLOUT_MIN_FEEDS;
   result["CLOUT_MINING_REWARD"] = CLOUT_MINING_REWARD;
   result["CLOUT_MINING_TIME"] = CLOUT_MINING_TIME;
   result["CLOUT_MIN_LIQUIDITY_REWARD"] = CLOUT_MIN_LIQUIDITY_REWARD;
   result["CLOUT_MIN_LIQUIDITY_REWARD_PERIOD_SEC"] = CLOUT_MIN_LIQUIDITY_REWARD_PERIOD_SEC;
   result["CLOUT_MIN_PAYOUT_CBD"] = CLOUT_MIN_PAYOUT_CBD;
   result["CLOUT_MIN_POW_REWARD"] = CLOUT_MIN_POW_REWARD;
   result["CLOUT_MIN_PRODUCER_REWARD"] = CLOUT_MIN_PRODUCER_REWARD;
   result["CLOUT_MIN_TRANSACTION_EXPIRATION_LIMIT"] = CLOUT_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result["CLOUT_MIN_TRANSACTION_SIZE_LIMIT"] = CLOUT_MIN_TRANSACTION_SIZE_LIMIT;
   result["CLOUT_MIN_UNDO_HISTORY"] = CLOUT_MIN_UNDO_HISTORY;
   result["CLOUT_NULL_ACCOUNT"] = CLOUT_NULL_ACCOUNT;
   result["CLOUT_NUM_INIT_MINERS"] = CLOUT_NUM_INIT_MINERS;
   result["CLOUT_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = CLOUT_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
   result["CLOUT_OWNER_AUTH_RECOVERY_PERIOD"] = CLOUT_OWNER_AUTH_RECOVERY_PERIOD;
   result["CLOUT_OWNER_CHALLENGE_COOLDOWN"] = CLOUT_OWNER_CHALLENGE_COOLDOWN;
   result["CLOUT_OWNER_CHALLENGE_FEE"] = CLOUT_OWNER_CHALLENGE_FEE;
   result["CLOUT_OWNER_UPDATE_LIMIT"] = CLOUT_OWNER_UPDATE_LIMIT;
   result["CLOUT_POST_AVERAGE_WINDOW"] = CLOUT_POST_AVERAGE_WINDOW;
   result["CLOUT_POST_REWARD_FUND_NAME"] = CLOUT_POST_REWARD_FUND_NAME;
   result["CLOUT_POST_WEIGHT_CONSTANT"] = CLOUT_POST_WEIGHT_CONSTANT;
   result["CLOUT_POW_APR_PERCENT"] = CLOUT_POW_APR_PERCENT;
   result["CLOUT_PRODUCER_APR_PERCENT"] = CLOUT_PRODUCER_APR_PERCENT;
   result["CLOUT_PROXY_TO_SELF_ACCOUNT"] = CLOUT_PROXY_TO_SELF_ACCOUNT;
   result["CLOUT_CBD_INTEREST_COMPOUND_INTERVAL_SEC"] = CLOUT_CBD_INTEREST_COMPOUND_INTERVAL_SEC;
   result["CLOUT_SECONDS_PER_YEAR"] = CLOUT_SECONDS_PER_YEAR;
   result["CLOUT_PROPOSAL_FUND_PERCENT_HF0"] = CLOUT_PROPOSAL_FUND_PERCENT_HF0;
   result["CLOUT_PROPOSAL_FUND_PERCENT_HF21"] = CLOUT_PROPOSAL_FUND_PERCENT_HF21;
   result["CLOUT_RECENT_RSHARES_DECAY_TIME_HF19"] = CLOUT_RECENT_RSHARES_DECAY_TIME_HF19;
   result["CLOUT_RECENT_RSHARES_DECAY_TIME_HF17"] = CLOUT_RECENT_RSHARES_DECAY_TIME_HF17;
   result["CLOUT_REVERSE_AUCTION_WINDOW_SECONDS_HF6"] = CLOUT_REVERSE_AUCTION_WINDOW_SECONDS_HF6;
   result["CLOUT_REVERSE_AUCTION_WINDOW_SECONDS_HF20"] = CLOUT_REVERSE_AUCTION_WINDOW_SECONDS_HF20;
   result["CLOUT_REVERSE_AUCTION_WINDOW_SECONDS_HF21"] = CLOUT_REVERSE_AUCTION_WINDOW_SECONDS_HF21;
   result["CLOUT_ROOT_POST_PARENT"] = CLOUT_ROOT_POST_PARENT;
   result["CLOUT_SAVINGS_WITHDRAW_REQUEST_LIMIT"] = CLOUT_SAVINGS_WITHDRAW_REQUEST_LIMIT;
   result["CLOUT_SAVINGS_WITHDRAW_TIME"] = CLOUT_SAVINGS_WITHDRAW_TIME;
   result["CLOUT_CBD_START_PERCENT_HF14"] = CLOUT_CBD_START_PERCENT_HF14;
   result["CLOUT_CBD_START_PERCENT_HF20"] = CLOUT_CBD_START_PERCENT_HF20;
   result["CLOUT_CBD_STOP_PERCENT_HF14"] = CLOUT_CBD_STOP_PERCENT_HF14;
   result["CLOUT_CBD_STOP_PERCENT_HF20"] = CLOUT_CBD_STOP_PERCENT_HF20;
   result["CLOUT_SECOND_CASHOUT_WINDOW"] = CLOUT_SECOND_CASHOUT_WINDOW;
   result["CLOUT_SOFT_MAX_COMMENT_DEPTH"] = CLOUT_SOFT_MAX_COMMENT_DEPTH;
   result["CLOUT_START_MINER_VOTING_BLOCK"] = CLOUT_START_MINER_VOTING_BLOCK;
   result["CLOUT_START_VESTING_BLOCK"] = CLOUT_START_VESTING_BLOCK;
   result["CLOUT_TEMP_ACCOUNT"] = CLOUT_TEMP_ACCOUNT;
   result["CLOUT_UPVOTE_LOCKOUT_HF7"] = CLOUT_UPVOTE_LOCKOUT_HF7;
   result["CLOUT_UPVOTE_LOCKOUT_HF17"] = CLOUT_UPVOTE_LOCKOUT_HF17;
   result["CLOUT_UPVOTE_LOCKOUT_SECONDS"] = CLOUT_UPVOTE_LOCKOUT_SECONDS;
   result["CLOUT_VESTING_FUND_PERCENT_HF16"] = CLOUT_VESTING_FUND_PERCENT_HF16;
   result["CLOUT_VESTING_WITHDRAW_INTERVALS"] = CLOUT_VESTING_WITHDRAW_INTERVALS;
   result["CLOUT_VESTING_WITHDRAW_INTERVALS_PRE_HF_16"] = CLOUT_VESTING_WITHDRAW_INTERVALS_PRE_HF_16;
   result["CLOUT_VESTING_WITHDRAW_INTERVAL_SECONDS"] = CLOUT_VESTING_WITHDRAW_INTERVAL_SECONDS;
   result["CLOUT_VOTE_DUST_THRESHOLD"] = CLOUT_VOTE_DUST_THRESHOLD;
   result["CLOUT_VOTING_MANA_REGENERATION_SECONDS"] = CLOUT_VOTING_MANA_REGENERATION_SECONDS;
   result["CLOUT_SYMBOL"] = CLOUT_SYMBOL;
   result["VESTS_SYMBOL"] = VESTS_SYMBOL;
   result["CLOUT_VIRTUAL_SCHEDULE_LAP_LENGTH"] = CLOUT_VIRTUAL_SCHEDULE_LAP_LENGTH;
   result["CLOUT_VIRTUAL_SCHEDULE_LAP_LENGTH2"] = CLOUT_VIRTUAL_SCHEDULE_LAP_LENGTH2;
   result["CLOUT_VOTES_PER_PERIOD_SMT_HF"] = CLOUT_VOTES_PER_PERIOD_SMT_HF;
   result["CLOUT_MAX_LIMIT_ORDER_EXPIRATION"] = CLOUT_MAX_LIMIT_ORDER_EXPIRATION;
   result["CLOUT_DELEGATION_RETURN_PERIOD_HF0"] = CLOUT_DELEGATION_RETURN_PERIOD_HF0;
   result["CLOUT_DELEGATION_RETURN_PERIOD_HF20"] = CLOUT_DELEGATION_RETURN_PERIOD_HF20;
   result["CLOUT_RD_MIN_DECAY_BITS"] = CLOUT_RD_MIN_DECAY_BITS;
   result["CLOUT_RD_MAX_DECAY_BITS"] = CLOUT_RD_MAX_DECAY_BITS;
   result["CLOUT_RD_DECAY_DENOM_SHIFT"] = CLOUT_RD_DECAY_DENOM_SHIFT;
   result["CLOUT_RD_MAX_POOL_BITS"] = CLOUT_RD_MAX_POOL_BITS;
   result["CLOUT_RD_MAX_BUDGET_1"] = CLOUT_RD_MAX_BUDGET_1;
   result["CLOUT_RD_MAX_BUDGET_2"] = CLOUT_RD_MAX_BUDGET_2;
   result["CLOUT_RD_MAX_BUDGET_3"] = CLOUT_RD_MAX_BUDGET_3;
   result["CLOUT_RD_MAX_BUDGET"] = CLOUT_RD_MAX_BUDGET;
   result["CLOUT_RD_MIN_DECAY"] = CLOUT_RD_MIN_DECAY;
   result["CLOUT_RD_MIN_BUDGET"] = CLOUT_RD_MIN_BUDGET;
   result["CLOUT_RD_MAX_DECAY"] = CLOUT_RD_MAX_DECAY;
   result["CLOUT_ACCOUNT_SUBSIDY_PRECISION"] = CLOUT_ACCOUNT_SUBSIDY_PRECISION;
   result["CLOUT_WITNESS_SUBSIDY_BUDGET_PERCENT"] = CLOUT_WITNESS_SUBSIDY_BUDGET_PERCENT;
   result["CLOUT_WITNESS_SUBSIDY_DECAY_PERCENT"] = CLOUT_WITNESS_SUBSIDY_DECAY_PERCENT;
   result["CLOUT_DEFAULT_ACCOUNT_SUBSIDY_DECAY"] = CLOUT_DEFAULT_ACCOUNT_SUBSIDY_DECAY;
   result["CLOUT_DEFAULT_ACCOUNT_SUBSIDY_BUDGET"] = CLOUT_DEFAULT_ACCOUNT_SUBSIDY_BUDGET;
   result["CLOUT_DECAY_BACKSTOP_PERCENT"] = CLOUT_DECAY_BACKSTOP_PERCENT;
   result["CLOUT_BLOCK_GENERATION_POSTPONED_TX_LIMIT"] = CLOUT_BLOCK_GENERATION_POSTPONED_TX_LIMIT;
   result["CLOUT_PENDING_TRANSACTION_EXECUTION_LIMIT"] = CLOUT_PENDING_TRANSACTION_EXECUTION_LIMIT;
   result["CLOUT_TREASURY_ACCOUNT"] = CLOUT_TREASURY_ACCOUNT;
   result["CLOUT_TREASURY_FEE"] = CLOUT_TREASURY_FEE;
   result["CLOUT_PROPOSAL_MAINTENANCE_PERIOD"] = CLOUT_PROPOSAL_MAINTENANCE_PERIOD;
   result["CLOUT_PROPOSAL_MAINTENANCE_CLEANUP"] = CLOUT_PROPOSAL_MAINTENANCE_CLEANUP;
   result["CLOUT_PROPOSAL_SUBJECT_MAX_LENGTH"] = CLOUT_PROPOSAL_SUBJECT_MAX_LENGTH;
   result["CLOUT_PROPOSAL_MAX_IDS_NUMBER"] = CLOUT_PROPOSAL_MAX_IDS_NUMBER;
   result["CLOUT_NETWORK_TYPE"] = CLOUT_NETWORK_TYPE;
   result["CLOUT_DB_FORMAT_VERSION"] = CLOUT_DB_FORMAT_VERSION;

   return result;
}

} } // clout::protocol
